### ISSUE TITLE
Unnecessary change?

### ISSUE THREAD

**Issue by chmeeedalf** [zeldin/chromium_be#1]
https://github.com/zeldin/chromium_be/blob/bd46e1fe8bb24e5205a89133cfed425057c6d17d/chromium-89.0.4389.114/skia.patch#L486

I don't think this block is necessary, since it's guarded by the #if defined(NEON) right above.

**Comment by zeldin** [comment]
Well, you'd need it for NEON on big endian ARM, no?

**Comment by chmeeedalf** [comment]
You would, but to the best of my knowledge there are no armeb uses with NEON, all ARMv7 and ARMv8 uses I've seen are LE, though the hardware may be capable of it.  I would be really interested to see an ARMv7 or ARMv8 used in big endian, though.

**Comment by mc-requtech** [comment]
@chmeedalf All ARMv8 are actually bi-endian.  If you have a Raspberry Pi 3 you can [try it out yourself](https://github.com/zeldin/linux-1/releases).  (I wouldn't recommend compiling Chromium on a Raspberry Pi 3 though, it takes 54 hours on my Jetson TX2, and I don't think a Pi would be any faster. :smile:)

**Comment by chmeeedalf** [comment]
I stand corrected.  Glad to see more big-endianness!
